require("core.plugin_config.cmp")
require("core.plugin_config.mason")
require("core.plugin_config.lualine")
require("core.plugin_config.toggle_term")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.complete")
require("core.plugin_config.gruvbox")
require("core.plugin_config.lspconfig")
