require("core.plugin_config.lualine")
require("core.plugin_config.toggle_term")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.complete")
require("core.plugin_config.catppuccin")
require("core.plugin_config.lspconfig")
